"""initial_schema

Revision ID: 83194d6f64c9
Revises: 
Create Date: 2026-04-26 21:48:57.791866

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# 👇 AÑADE ESTA LÍNEA
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '83194d6f64c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
                    sa.Column('name', sa.String(length=200), nullable=False,
                              comment='Display name shown in the UI and on patient-facing pages.'),
                    sa.Column('slug', sa.String(length=80), nullable=False,
                              comment='URL-safe identifier used in magic links: /book/{slug}/...'),
                    sa.Column('country_code', sa.String(length=2), server_default='MX', nullable=False,
                              comment='ISO 3166-1 alpha-2. Drives timezone defaults and tax rules.'),
                    sa.Column('timezone', sa.String(length=60),
                              server_default='America/Mexico_City', nullable=False),
                    sa.Column('logo_s3_key', sa.String(length=500), nullable=True,
                              comment='S3 object key for the clinic logo (served via presigned URL).'),
                    sa.Column('is_active', sa.Boolean(),
                              server_default=sa.text('true'), nullable=False),
                    sa.Column('plan_tier', sa.String(length=30),
                              server_default='starter', nullable=False),
                    sa.Column('subscription_status', sa.String(length=30), server_default='trialing', nullable=False,
                              comment='Synced from Stripe webhooks. Drives access control in get_clinic().'),
                    sa.Column('stripe_customer_id', sa.String(length=50), nullable=True,
                              comment='cus_* Stripe customer ID. Set on first checkout.'),
                    sa.Column('stripe_subscription_id', sa.String(length=50), nullable=True,
                              comment='sub_* Stripe subscription ID. Null during trial.'),
                    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True,
                              comment='When NULL, the clinic is on a paid plan.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clinics_slug'), 'clinics', ['slug'], unique=True)
    op.create_index(op.f('ix_clinics_stripe_customer_id'),
                    'clinics', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_clinics_stripe_subscription_id'),
                    'clinics', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_clinics_subscription_status'),
                    'clinics', ['subscription_status'], unique=False)
    op.create_table('patients',
                    sa.Column('full_name_enc', app.db.types.EncryptedString(
                    ), nullable=False, comment='Encrypted full legal name.'),
                    sa.Column('full_name_search_hash', sa.String(length=64), nullable=False,
                              comment='HMAC-SHA256(lower(full_name.strip()), SEARCH_HMAC_KEY). Exact-match search: WHERE clinic_id=? AND full_name_search_hash=?'),
                    sa.Column('phone_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Encrypted phone number. Normalise to E.164 before encrypting.'),
                    sa.Column('phone_search_hash', sa.String(length=64), nullable=True,
                              comment='HMAC-SHA256 of digits-only phone. Allows lookup by phone number.'),
                    sa.Column('email_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Encrypted email. Used only for notification sending.'),
                    sa.Column('date_of_birth_enc', app.db.types.EncryptedString(
                    ), nullable=True, comment="Encrypted ISO-8601 date string: '1990-04-15'."),
                    sa.Column('gender_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Encrypted. Values: male, female, non_binary, prefer_not_to_say.'),
                    sa.Column('address_enc', app.db.types.EncryptedString(),
                              nullable=True, comment='Encrypted full address (free text).'),
                    sa.Column('blood_type_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Encrypted. Values: A+, A-, B+, B-, AB+, AB-, O+, O-.'),
                    sa.Column('allergies_enc', app.db.types.EncryptedJSON(), nullable=True,
                              comment='Encrypted JSONB. Schema: {"medications": ["penicillin"], "foods": [], "environmental": []}. Stored as JSON so it can be extended without schema migration.'),
                    sa.Column('notes_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='General intake notes visible to all clinic staff. Per-visit clinical notes belong in MedicalRecord, not here.'),
                    sa.Column('emergency_contact_name_enc',
                              app.db.types.EncryptedString(), nullable=True),
                    sa.Column('emergency_contact_phone_enc',
                              app.db.types.EncryptedString(), nullable=True),
                    sa.Column('key_version', sa.SmallInteger(), server_default='0', nullable=False,
                              comment='Index of the encryption key used for this row. Background job: UPDATE patients SET ... WHERE key_version < :current'),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False,
                              comment='False = soft-deleted. Keeps audit trail and medical records intact.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_patients_clinic_active', 'patients',
                    ['clinic_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_patients_clinic_id'),
                    'patients', ['clinic_id'], unique=False)
    op.create_index('ix_patients_clinic_keyver', 'patients', [
                    'clinic_id', 'key_version'], unique=False)
    op.create_index('ix_patients_clinic_name_hash', 'patients', [
                    'clinic_id', 'full_name_search_hash'], unique=False)
    op.create_index('ix_patients_clinic_phone_hash', 'patients', [
                    'clinic_id', 'phone_search_hash'], unique=False)
    op.create_index(op.f('ix_patients_key_version'),
                    'patients', ['key_version'], unique=False)
    op.create_table('users',
                    sa.Column('email_enc', app.db.types.EncryptedString(), nullable=False,
                              comment='AES-256-GCM encrypted email. Never query this column directly.'),
                    sa.Column('email_search_hash', sa.String(length=64), nullable=False,
                              comment='HMAC-SHA256(lower(email), SEARCH_HMAC_KEY). Used for login lookup: WHERE clinic_id=? AND email_search_hash=?'),
                    sa.Column('full_name_enc', app.db.types.EncryptedString(), nullable=False,
                              comment='Encrypted display name. Decrypted only when rendering UI.'),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False,
                              comment='Argon2id hash produced by passlib. Format: $argon2id$v=19$m=65536,t=2,p=1$...'),
                    sa.Column('role', sa.String(length=20), server_default='assistant', nullable=False,
                              comment='One of: owner, doctor, assistant. Enforced by require_role() in deps.py.'),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False,
                              comment='Soft-disable without deleting. get_current_user() rejects inactive users.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_users_clinic_email_hash', 'users', [
                    'clinic_id', 'email_search_hash'], unique=True)
    op.create_index(op.f('ix_users_clinic_id'), 'users',
                    ['clinic_id'], unique=False)
    op.create_index('ix_users_clinic_role', 'users', [
                    'clinic_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
                    sa.Column('actor_id', sa.UUID(
                    ), nullable=True, comment='The user who triggered this event. NULL = system/unauthenticated.'),
                    sa.Column('actor_role', sa.String(length=20), nullable=True,
                              comment="Denormalised role snapshot at event time. Preserved even if the user's role changes later."),
                    sa.Column('event_type', sa.String(length=80), nullable=False,
                              comment='Dot-notation event type. See EventType class for registry.'),
                    sa.Column('entity_type', sa.String(length=50), nullable=False,
                              comment='Affected entity class name: Patient, Appointment, MedicalRecord, …'),
                    sa.Column('entity_id', sa.UUID(), nullable=True,
                              comment='PK of the affected row. Indexed for entity-history lookups.'),
                    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'NOW()'), nullable=False, comment='Application-layer timestamp of the event (not DB insert time).'),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False,
                              comment='CloudEvents-compatible envelope. PII values must be masked — only field names listed in masked_fields.'),
                    sa.Column('ip_address', sa.String(
                        length=45), nullable=True),
                    sa.Column('user_agent', sa.String(
                        length=300), nullable=True),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['actor_id'], ['users.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_audit_clinic_entity', 'audit_logs', [
                    'clinic_id', 'entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_clinic_eventtype', 'audit_logs', [
                    'clinic_id', 'event_type', 'occurred_at'], unique=False)
    op.create_index('ix_audit_clinic_occurred', 'audit_logs', [
                    'clinic_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_clinic_id'),
                    'audit_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'),
                    'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'),
                    'audit_logs', ['event_type'], unique=False)
    op.create_table('doctors',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('specialty', sa.String(length=120), nullable=False,
                              comment='Displayed on patient-facing booking page.'),
                    sa.Column('license_number', sa.String(length=50), nullable=True,
                              comment='Professional medical license (Cédula Profesional in Mexico).'),
                    sa.Column('bio', sa.String(length=1000), nullable=True,
                              comment='Short public bio for the booking page.'),
                    sa.Column('avatar_s3_key', sa.String(length=500), nullable=True,
                              comment='S3 key for profile photo, served via presigned URL.'),
                    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False,
                              comment="Weekly schedule as JSONB. Schema: {day: [{start: 'HH:MM', end: 'HH:MM'}]}. Empty list means day off."),
                    sa.Column('appointment_duration_minutes', sa.Integer(), server_default='30',
                              nullable=False, comment='Default slot length used by the booking grid UI.'),
                    sa.Column('is_accepting_patients', sa.Boolean(), server_default=sa.text('true'), nullable=False,
                              comment='False hides this doctor from the magic-link booking page. Useful for sabbaticals, maternity leave, etc.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_doctors_clinic_accepting', 'doctors', [
                    'clinic_id', 'is_accepting_patients'], unique=False)
    op.create_index(op.f('ix_doctors_clinic_id'),
                    'doctors', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctors_user_id'),
                    'doctors', ['user_id'], unique=True)
    op.create_table('appointments',
                    sa.Column('doctor_id', sa.UUID(), nullable=False,
                              comment='The doctor who will see the patient.'),
                    sa.Column('patient_id', sa.UUID(), nullable=False,
                              comment='Must belong to the same clinic (enforced in service layer).'),
                    sa.Column('created_by_id', sa.UUID(), nullable=True,
                              comment='Staff user who created the appointment. NULL = self-booked via magic link.'),
                    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False,
                              comment='Appointment start. Always stored in UTC.'),
                    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False,
                              comment="Appointment end. Derived from doctor.appointment_duration_minutes but stored explicitly so duration changes don't affect existing records."),
                    sa.Column('status', sa.String(length=30),
                              server_default='scheduled', nullable=False),
                    sa.Column('notes_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Internal notes visible to doctor/owner only. Encrypted.'),
                    sa.Column('reason', sa.String(length=300), nullable=True,
                              comment='Brief reason shown in notifications and booking confirmations. Must not contain clinical information — that goes in notes_enc.'),
                    sa.Column('key_version', sa.SmallInteger(),
                              server_default='0', nullable=False),
                    sa.Column('magic_token', sa.String(length=36), nullable=True,
                              comment='UUID v4 token for patient-facing cancel/reschedule link. Generated on creation; cleared after use or expiry.'),
                    sa.Column('magic_token_expires_at', sa.DateTime(timezone=True),
                              nullable=True, comment='Token expiry. Typically created_at + 72 h.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(
                        ['patient_id'], ['patients.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_appointments_clinic_id'),
                    'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_magic_token'),
                    'appointments', ['magic_token'], unique=True)
    op.create_index(op.f('ix_appointments_status'),
                    'appointments', ['status'], unique=False)
    op.create_index('ix_appts_clinic_patient', 'appointments', [
                    'clinic_id', 'patient_id', 'starts_at'], unique=False)
    op.create_index('ix_appts_clinic_starts_status', 'appointments', [
                    'clinic_id', 'starts_at', 'status'], unique=False)
    op.create_index('ix_appts_doctor_starts', 'appointments', [
                    'clinic_id', 'doctor_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index('ix_appts_magic_token', 'appointments',
                    ['magic_token'], unique=False)
    op.create_table('medical_records',
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('appointment_id', sa.UUID(), nullable=True,
                              comment='Null for records created outside of a scheduled appointment.'),
                    sa.Column('diagnosis_enc', app.db.types.EncryptedString(), nullable=True,
                              comment='Primary diagnosis (ICD-10 code + description, encrypted).'),
                    sa.Column('treatment_enc', app.db.types.EncryptedString(
                    ), nullable=True, comment='Treatment plan / prescribed procedures.'),
                    sa.Column('prescription_enc', app.db.types.EncryptedJSON(), nullable=True,
                              comment='Encrypted JSONB. Schema: [{"drug": "Amoxicillin", "dose": "500mg", "freq": "8h", "days": 7}]'),
                    sa.Column('observations_enc', app.db.types.EncryptedString(
                    ), nullable=True, comment='Free-text doctor observations. Not shown to patients.'),
                    sa.Column('vitals_enc', app.db.types.EncryptedJSON(), nullable=True,
                              comment='Encrypted JSONB. Schema: {"weight_kg": 70, "height_cm": 175, "bp_systolic": 120, "bp_diastolic": 80, "temp_c": 36.5, "hr_bpm": 72}'),
                    sa.Column('s3_pdf_key', sa.String(length=500), nullable=True,
                              comment="S3 object key for the scanned/generated PDF of this record. Format: 'records/{clinic_id}/{patient_id}/{record_id}.pdf'. Access only via S3Service.generate_download_presigned_url()."),
                    sa.Column('is_signed', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='Once True, clinical content fields become immutable (enforced at service layer — the DB allows updates for corrections).'),
                    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True,
                              comment='Set when doctor signs off. Required by NOM-024.'),
                    sa.Column('signed_by_id', sa.UUID(), nullable=True,
                              comment='User (doctor) who signed off. Immutable after set.'),
                    sa.Column('key_version', sa.SmallInteger(),
                              server_default='0', nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(['appointment_id'], [
                        'appointments.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(
                        ['patient_id'], ['patients.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(
                        ['signed_by_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('appointment_id')
                    )
    op.create_index(op.f('ix_medical_records_clinic_id'),
                    'medical_records', ['clinic_id'], unique=False)
    op.create_index('ix_medrecords_clinic_doctor', 'medical_records', [
                    'clinic_id', 'doctor_id'], unique=False)
    op.create_index('ix_medrecords_clinic_keyver', 'medical_records', [
                    'clinic_id', 'key_version'], unique=False)
    op.create_index('ix_medrecords_clinic_patient_created', 'medical_records', [
                    'clinic_id', 'patient_id', 'created_at'], unique=False)
    op.create_table('notifications',
                    sa.Column('appointment_id', sa.UUID(), nullable=True),
                    sa.Column('channel', sa.String(length=20),
                              nullable=False, comment='email | whatsapp | sms'),
                    sa.Column('notification_type', sa.String(length=50), nullable=False,
                              comment='Drives template selection in notification_service.py.'),
                    sa.Column('recipient_enc', app.db.types.EncryptedString(), nullable=True,
                              comment="Encrypted email address or E.164 phone number. Kept here so retry doesn't need to re-join Patient."),
                    sa.Column('status', sa.String(length=20),
                              server_default='pending', nullable=False),
                    sa.Column('attempt_count', sa.SmallInteger(), server_default='0',
                              nullable=False, comment='Incremented on each delivery attempt.'),
                    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True,
                              comment='Set on first successful delivery.'),
                    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False,
                              comment='Channel-specific data. Must NOT contain PII values. EMAIL: {subject, template, provider_msg_id, error}. WHATSAPP: {wa_link, message_preview}.'),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.ForeignKeyConstraint(['appointment_id'], [
                        'appointments.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_appointment_id'),
                    'notifications', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_notifications_clinic_id'),
                    'notifications', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'),
                    'notifications', ['status'], unique=False)
    op.create_index('ix_notifs_appt_channel', 'notifications', [
                    'appointment_id', 'channel'], unique=False)
    op.create_index('ix_notifs_clinic_status_created', 'notifications', [
                    'clinic_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifs_clinic_status_created',
                  table_name='notifications')
    op.drop_index('ix_notifs_appt_channel', table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_clinic_id'),
                  table_name='notifications')
    op.drop_index(op.f('ix_notifications_appointment_id'),
                  table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_medrecords_clinic_patient_created',
                  table_name='medical_records')
    op.drop_index('ix_medrecords_clinic_keyver', table_name='medical_records')
    op.drop_index('ix_medrecords_clinic_doctor', table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_clinic_id'),
                  table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index('ix_appts_magic_token', table_name='appointments')
    op.drop_index('ix_appts_doctor_starts', table_name='appointments')
    op.drop_index('ix_appts_clinic_starts_status', table_name='appointments')
    op.drop_index('ix_appts_clinic_patient', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_magic_token'),
                  table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_clinic_id'), table_name='doctors')
    op.drop_index('ix_doctors_clinic_accepting', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_index('ix_audit_clinic_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_clinic_eventtype', table_name='audit_logs')
    op.drop_index('ix_audit_clinic_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_users_clinic_role', table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_index('ix_users_clinic_email_hash', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_key_version'), table_name='patients')
    op.drop_index('ix_patients_clinic_phone_hash', table_name='patients')
    op.drop_index('ix_patients_clinic_name_hash', table_name='patients')
    op.drop_index('ix_patients_clinic_keyver', table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_index('ix_patients_clinic_active', table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_clinics_subscription_status'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_stripe_subscription_id'),
                  table_name='clinics')
    op.drop_index(op.f('ix_clinics_stripe_customer_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_slug'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
