"""
app/models/medical_record.py
──────────────────────────────────────────────────────────────────────────────
MedicalRecord — per-visit clinical record (Expediente Médico).

One MedicalRecord per appointment visit. Contains:
  • Structured clinical data (encrypted): diagnosis, treatment, prescription
  • Unstructured: free-text observations (encrypted)
  • PDF attachment: stored in S3; accessed only via presigned URLs (see S3Service)

NOM-024-SSA3-2010 compliance notes:
  • All clinical data must be encrypted at rest → EncryptedString / EncryptedJSON
  • Records must be immutable after sign-off → `is_signed` flag + signed_at timestamp
  • Retain records for at least 5 years after last patient visit
  • Access must be logged → AuditLog entry on every READ and WRITE

PDF workflow:
  1. Doctor clicks "Upload file" → frontend calls POST /records/{id}/upload-url
  2. s3_service.generate_upload_presigned_url() returns a 5-min PUT URL
  3. Frontend uploads directly to S3 (no data passes through the API server)
  4. Frontend calls PATCH /records/{id} with { s3_pdf_key: "key" }
  5. On download: GET /records/{id}/download-url → presigned GET URL (5 min TTL)

The s3_pdf_key is the S3 object key (not a full URL) so we can change buckets
or CDN without a DB migration.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, SmallInteger, String, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.types import EncryptedString, NullableEncryptedString, EncryptedJSON
from app.models.base import TenantBase

if TYPE_CHECKING:
    from app.models.clinic import Clinic
    from app.models.patient import Patient
    from app.models.doctor import Doctor
    from app.models.appointment import Appointment


class MedicalRecord(TenantBase):
    """
    Clinical record for a single visit. Inherits from TenantBase.

    All clinical fields are encrypted. The `s3_pdf_key` points to a private
    S3 object (never public) accessible only via presigned URLs generated by
    the backend after RBAC checks.
    """

    __tablename__ = "medical_records"

    # ── Participants ──────────────────────────────────────────────────────────
    patient_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="RESTRICT"),
        nullable=False,
    )

    doctor_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("doctors.id", ondelete="RESTRICT"),
        nullable=False,
    )

    appointment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("appointments.id", ondelete="SET NULL"),
        nullable=True,
        unique=True,            # one record per appointment
        comment="Null for records created outside of a scheduled appointment.",
    )

    # ── Clinical content (all encrypted) ─────────────────────────────────────
    diagnosis_enc: Mapped[Optional[str]] = mapped_column(
        NullableEncryptedString,
        nullable=True,
        comment="Primary diagnosis (ICD-10 code + description, encrypted).",
    )

    treatment_enc: Mapped[Optional[str]] = mapped_column(
        NullableEncryptedString,
        nullable=True,
        comment="Treatment plan / prescribed procedures.",
    )

    prescription_enc: Mapped[Optional[dict]] = mapped_column(
        EncryptedJSON,
        nullable=True,
        comment=(
            "Encrypted JSONB. Schema: "
            '[{"drug": "Amoxicillin", "dose": "500mg", "freq": "8h", "days": 7}]'
        ),
    )

    observations_enc: Mapped[Optional[str]] = mapped_column(
        NullableEncryptedString,
        nullable=True,
        comment="Free-text doctor observations. Not shown to patients.",
    )

    vitals_enc: Mapped[Optional[dict]] = mapped_column(
        EncryptedJSON,
        nullable=True,
        comment=(
            "Encrypted JSONB. Schema: "
            '{"weight_kg": 70, "height_cm": 175, "bp_systolic": 120, '
            '"bp_diastolic": 80, "temp_c": 36.5, "hr_bpm": 72}'
        ),
    )

    # ── PDF attachment (S3) ───────────────────────────────────────────────────
    s3_pdf_key: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment=(
            "S3 object key for the scanned/generated PDF of this record. "
            "Format: 'records/{clinic_id}/{patient_id}/{record_id}.pdf'. "
            "Access only via S3Service.generate_download_presigned_url()."
        ),
    )

    # ── Sign-off / immutability ───────────────────────────────────────────────
    is_signed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment=(
            "Once True, clinical content fields become immutable "
            "(enforced at service layer — the DB allows updates for corrections)."
        ),
    )

    signed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set when doctor signs off. Required by NOM-024.",
    )

    signed_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User (doctor) who signed off. Immutable after set.",
    )

    # ── Key rotation ──────────────────────────────────────────────────────────
    key_version: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        default=0,
        server_default="0",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    patient: Mapped["Patient"] = relationship(
        "Patient",
        back_populates="medical_records",
        lazy="select",
    )

    doctor: Mapped["Doctor"] = relationship(
        "Doctor",
        back_populates="medical_records",
        lazy="select",
    )

    appointment: Mapped[Optional["Appointment"]] = relationship(
        "Appointment",
        back_populates="medical_records",
        lazy="select",
    )

    # ── Composite indexes ─────────────────────────────────────────────────────
    __table_args__ = (
        # Patient timeline (most common access pattern)
        Index(
            "ix_medrecords_clinic_patient_created",
            "clinic_id",
            "patient_id",
            "created_at",
        ),
        # Doctor's records (secondary access pattern)
        Index(
            "ix_medrecords_clinic_doctor",
            "clinic_id",
            "doctor_id",
        ),
        # Key rotation job
        Index(
            "ix_medrecords_clinic_keyver",
            "clinic_id",
            "key_version",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<MedicalRecord id={self.id} patient={self.patient_id} "
            f"signed={self.is_signed}>"
        )
